/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sameer_2;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PatientDataEntryForm extends javax.swing.JFrame {

    String PatientID, PatientName, PatientAge, PatientGender, PatientPhoneNo, PatientRefBy;
    String chemDep[] = new String[6];
    String hemDep, micDep, bbDep;

    public PatientDataEntryForm() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelMax = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RefBy = new javax.swing.JTextField();
        AdminSignUpButton = new javax.swing.JButton();
        AdminLoginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AdminSignUpButton1 = new javax.swing.JButton();
        genderFemale = new javax.swing.JRadioButton();
        genderMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ch1 = new javax.swing.JCheckBox();
        ch2 = new javax.swing.JCheckBox();
        ch3 = new javax.swing.JCheckBox();
        ch4 = new javax.swing.JCheckBox();
        ch5 = new javax.swing.JCheckBox();
        ch6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        hem1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        mic1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        bb1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 245, 145));

        jLabelMax.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMax.setText("X");
        jLabelMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaxMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient Data Entry and Test Selection Form");

        jLabelMin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 183, 255));
        jLabel4.setText("Age");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 170, 40, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 183, 255));
        jLabel5.setText("Patient ID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 40, 90, 30);

        RefBy.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RefBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefByActionPerformed(evt);
            }
        });
        jPanel2.add(RefBy);
        RefBy.setBounds(140, 340, 180, 30);

        AdminSignUpButton.setBackground(new java.awt.Color(255, 0, 0));
        AdminSignUpButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AdminSignUpButton.setText("Delete");
        AdminSignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminSignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminSignUpButtonMouseClicked(evt);
            }
        });
        jPanel2.add(AdminSignUpButton);
        AdminSignUpButton.setBounds(40, 420, 80, 40);

        AdminLoginButton.setBackground(new java.awt.Color(0, 255, 51));
        AdminLoginButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AdminLoginButton.setText("Save");
        AdminLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AdminLoginButton);
        AdminLoginButton.setBounds(240, 420, 80, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 183, 255));
        jLabel6.setText("Referred by:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 340, 100, 30);

        ID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel2.add(ID);
        ID.setBounds(140, 40, 180, 30);

        fullName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameActionPerformed(evt);
            }
        });
        jPanel2.add(fullName);
        fullName.setBounds(140, 100, 180, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 183, 255));
        jLabel7.setText("Full name");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 100, 80, 30);

        Age.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        jPanel2.add(Age);
        Age.setBounds(140, 160, 180, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 183, 255));
        jLabel8.setText("Gender");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 230, 80, 30);

        AdminSignUpButton1.setBackground(new java.awt.Color(255, 255, 0));
        AdminSignUpButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AdminSignUpButton1.setText("Search");
        AdminSignUpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminSignUpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminSignUpButton1MouseClicked(evt);
            }
        });
        jPanel2.add(AdminSignUpButton1);
        AdminSignUpButton1.setBounds(140, 420, 80, 40);

        genderFemale.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(genderFemale);
        genderFemale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        genderFemale.setForeground(new java.awt.Color(255, 255, 255));
        genderFemale.setText("Female");
        genderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(genderFemale);
        genderFemale.setBounds(239, 230, 80, 20);

        genderMale.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(genderMale);
        genderMale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        genderMale.setForeground(new java.awt.Color(255, 255, 255));
        genderMale.setText("Male");
        genderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderMaleActionPerformed(evt);
            }
        });
        jPanel2.add(genderMale);
        genderMale.setBounds(140, 230, 80, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 183, 255));
        jLabel9.setText("Phone no:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 280, 80, 30);

        PhoneNo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        PhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoActionPerformed(evt);
            }
        });
        jPanel2.add(PhoneNo);
        PhoneNo.setBounds(140, 280, 180, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Chemistry");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(430, 30, 80, 30);

        ch1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch1.setText("Lipid Profile");
        jPanel2.add(ch1);
        ch1.setBounds(420, 70, 93, 27);

        ch2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch2.setText("Plasma Glucose (Random)");
        jPanel2.add(ch2);
        ch2.setBounds(420, 100, 180, 27);

        ch3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch3.setText("Serum Insulin (Fasting)");
        jPanel2.add(ch3);
        ch3.setBounds(420, 130, 180, 27);

        ch4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch4.setText("HBsAg");
        jPanel2.add(ch4);
        ch4.setBounds(420, 160, 90, 27);

        ch5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch5.setText("Anti-HCV");
        jPanel2.add(ch5);
        ch5.setBounds(420, 190, 90, 27);

        ch6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ch6.setText("Glycosylated Hemoglobin (Hb1AC)");
        ch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch6ActionPerformed(evt);
            }
        });
        jPanel2.add(ch6);
        ch6.setBounds(420, 220, 230, 27);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hematology");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(690, 30, 100, 30);

        hem1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        hem1.setText("Blood C/E (Complete CBC)");
        jPanel2.add(hem1);
        hem1.setBounds(690, 70, 175, 27);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Microbiology");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(420, 290, 110, 30);

        mic1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mic1.setText("Urine C/E (Complete, Analysis)");
        jPanel2.add(mic1);
        mic1.setBounds(420, 330, 203, 27);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood Bank");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(690, 290, 90, 30);

        bb1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bb1.setText("Blood Group & Rh Factor");
        bb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb1ActionPerformed(evt);
            }
        });
        jPanel2.add(bb1);
        bb1.setBounds(690, 330, 180, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaxMouseClicked
        System.exit(0); // On click form exits

    }//GEN-LAST:event_jLabelMaxMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED); // On click form minimizes
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void RefByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefByActionPerformed

    private void AdminSignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminSignUpButtonMouseClicked

    }//GEN-LAST:event_AdminSignUpButtonMouseClicked

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void AdminSignUpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminSignUpButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminSignUpButton1MouseClicked

    private void PhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoActionPerformed

    private void AdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginButtonActionPerformed

        FinalReportForm FRFObj = new FinalReportForm();
        DefaultTableModel DTMObj = (DefaultTableModel)FRFObj.jTable1.getModel();
        if (ch1.isSelected() == false && ch2.isSelected() == false && ch3.isSelected() == false && ch4.isSelected() == false && ch5.isSelected() == false && ch6.isSelected() == false && hem1.isSelected() == false && mic1.isSelected() == false && bb1.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Atleast one test must be selected", "Test Not Selected Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (ch1.isSelected() == true) {
                chemDep[0] = ch1.getText();
                DTMObj.setValueAt(chemDep[0], 0, 0);
                DTMObj.setValueAt("< 150 mg/dL", 0, 2);
            }
            if (ch2.isSelected() == true) {
                chemDep[1] = ch2.getText();
                DTMObj.setValueAt(chemDep[1], 1, 0);
                DTMObj.setValueAt("< 200 mg/dL", 1, 2);
                
            }
            if (ch3.isSelected() == true) {
                chemDep[2] = ch3.getText();
                DTMObj.setValueAt(chemDep[2], 2, 0);
                DTMObj.setValueAt("< 25 mlU/L", 2, 2);
            }
            if (ch4.isSelected() == true) {
                chemDep[3] = ch4.getText();
                DTMObj.setValueAt(chemDep[3], 3, 0);
                DTMObj.setValueAt("< 5 is -ve", 3, 2);
            }
            if (ch5.isSelected() == true) {
                chemDep[4] = ch5.getText();
                DTMObj.setValueAt(chemDep[4], 4, 0);
                DTMObj.setValueAt("1-100,000,000 IU/mL", 4, 2);
            }
            if (ch6.isSelected() == true) {
                chemDep[5] = ch6.getText();
                DTMObj.setValueAt(chemDep[5], 5, 0);
                DTMObj.setValueAt("> 4% and < 5.6%", 5, 2);
            }
            if (hem1.isSelected() == true) {
                hemDep = hem1.getText();
                DTMObj.setValueAt(hemDep, 6, 0);
                DTMObj.setValueAt("Men: 140-175 g/L, Women: 123-153g/L", 6, 2);
            }
            if (mic1.isSelected() == true) {
                micDep = mic1.getText();
                DTMObj.setValueAt(micDep, 7, 0);
                DTMObj.setValueAt("ph: 4.5-8.0", 7, 2);
            }
            if (bb1.isSelected() == true) {
                bbDep = bb1.getText();
                DTMObj.setValueAt(bbDep, 8, 0);
                DTMObj.setValueAt("Ideal is -ve", 8, 2);
            }
        }
        if (ID.getText() == null || fullName.getText() == null || Age.getText() == null || RefBy.getText() == null || PhoneNo.getText() == null || (genderMale.isSelected() == false && genderFemale.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory to be filled", "Incomplete Data Error", JOptionPane.ERROR_MESSAGE);
        } else {
            PatientID = ID.getText();
            PatientName = fullName.getText();
            PatientAge = Age.getText();
            if (genderMale.isSelected()) {
                PatientGender = genderMale.getText();
            } else {
                PatientGender = genderFemale.getText();
            }
            PatientPhoneNo = PhoneNo.getText();
            PatientRefBy = RefBy.getText();

            
            FRFObj.txtFieldID.setText(PatientID);
            FRFObj.txtFieldName.setText(PatientName);
            FRFObj.txtFieldAge.setText(PatientAge);
            FRFObj.txtFieldGender.setText(PatientGender);
            FRFObj.txtFieldPhoneNo.setText(PatientPhoneNo);
            FRFObj.txtFieldRefBy.setText(PatientRefBy);

            FRFObj.setVisible(true);
            FRFObj.pack();
            FRFObj.setLocationRelativeTo(null);
            FRFObj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();

        }

    }//GEN-LAST:event_AdminLoginButtonActionPerformed

    private void bb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bb1ActionPerformed

    private void genderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderMaleActionPerformed

    private void genderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleActionPerformed

    private void ch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDataEntryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginButton;
    private javax.swing.JButton AdminSignUpButton;
    private javax.swing.JButton AdminSignUpButton1;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField RefBy;
    private javax.swing.JCheckBox bb1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch2;
    private javax.swing.JCheckBox ch3;
    private javax.swing.JCheckBox ch4;
    private javax.swing.JCheckBox ch5;
    private javax.swing.JCheckBox ch6;
    private javax.swing.JTextField fullName;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.JCheckBox hem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox mic1;
    // End of variables declaration//GEN-END:variables
}
