/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sample_11;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Haseeb
 */
public class info_form extends javax.swing.JFrame {

    private String movie_id;
    private String movie_name;
    private String movie_price;
    private String movie_quantity;

    /** Creates new form info_form */
    public info_form() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rent_button = new javax.swing.JButton();
        name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnic_field = new javax.swing.JTextField();
        back_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        movie_detials = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        rent_button.setText("Rent");
        rent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rent_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("CNIC");

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Movie Details");

        movie_detials.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(47, 47, 47)
                            .addComponent(movie_detials))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(back_button)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rent_button))
                                .addComponent(cnic_field, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cnic_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(movie_detials))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rent_button)
                    .addComponent(back_button))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Home_Screen().setVisible(true);

            }
        });
    }//GEN-LAST:event_back_buttonActionPerformed

    private void rent_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rent_buttonActionPerformed
        // TODO add your handling code here:
        
        try 
        {
            if(cnic_field.getText().equals("") || name_field.getText().equals("")  )
            {
                JOptionPane.showMessageDialog(this, "Please Enter the data first");
                return;

            }
            
            Connection   connection = DriverManager.getConnection("jdbc:sqlite:data.db");
            Statement statement = connection.createStatement();
            
            if(Integer.parseInt(movie_quantity)==0 || name_field.getText().equals("") ||  cnic_field.getText().equals("") )
                throw  new SQLException();
//            System.out.println(("INSERT INTO movie_record(movie_id,person_name,cnic,returned,movie_purchased,total_amount) VALUES ( "+ movie_id + ", '" + name_field.getText()+ "', ' "+ cnic_field.getText() + "', "+ "'rented'" +","+1+", "+ movie_price +  "   )"));
            statement.execute("INSERT INTO movie_record(movie_id,person_name,cnic,returned,movie_purchased,total_amount) VALUES ( "+ movie_id + ", '" + name_field.getText()+ "', ' "+ cnic_field.getText() + "', "+ "'rented'" +","+1+", "+ movie_price +  "   )");
            int new_quantity = Integer.parseInt(movie_quantity) -1;
            statement.close();
            
            statement = connection.createStatement();
            statement.executeUpdate("Update movie set quantity = " + new_quantity + "   where id =  " + movie_id+"  ;"); // to be chekced 
            statement.close();
        
            connection.close();
        
            
            JOptionPane.showMessageDialog(this, "Movie has been rented");
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Screen.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "Data was not updated");
        }
        
    }//GEN-LAST:event_rent_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               screen =   new info_form();
               screen.setVisible(true);
            }
        });
    }
          static   JFrame screen ;
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JTextField cnic_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel movie_detials;
    private javax.swing.JTextField name_field;
    private javax.swing.JButton rent_button;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent clone_window = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clone_window);
    }

    void setMovie_data(String movie_id, String movie_name, String movie_price, String movie_quantity)
    {
        movie_detials.setText(movie_id + " "+ movie_name + " "+ movie_price + " " + movie_quantity   );
        this.movie_id  = movie_id;
        this.movie_name  = movie_name;
        this.movie_price = movie_price;
        this.movie_quantity  = movie_quantity;
        
        
    }

}
