/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample_11;

import javax.swing.JFrame;

/**
 *
 * @author Haseeb
 */
public class Main_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Main_Screen
     */
    public Main_Screen() {
        initComponents();
            this.screen = this;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_movie = new javax.swing.JButton();
        rent_movie = new javax.swing.JButton();
        Return_btn = new javax.swing.JButton();
        all_btn = new javax.swing.JButton();
        all_rec_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        setForeground(new java.awt.Color(255, 102, 51));

        add_movie.setText("Add Movie");
        add_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_movieActionPerformed(evt);
            }
        });

        rent_movie.setText("Rent Movie");
        rent_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rent_movieActionPerformed(evt);
            }
        });

        Return_btn.setText("Return Movie");
        Return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_btnActionPerformed(evt);
            }
        });

        all_btn.setText("All Movies");
        all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_btnActionPerformed(evt);
            }
        });

        all_rec_btn.setText("All Records");
        all_rec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_rec_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Cinema House");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(add_movie)
                        .addGap(44, 44, 44)
                        .addComponent(rent_movie)
                        .addGap(38, 38, 38)
                        .addComponent(Return_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(all_btn)
                        .addGap(67, 67, 67)
                        .addComponent(all_rec_btn)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_movie)
                    .addComponent(rent_movie)
                    .addComponent(Return_btn))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(all_btn)
                    .addComponent(all_rec_btn))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_movieActionPerformed
            new Add_Movie().setVisible(true);
            screen.setVisible(false);
    }//GEN-LAST:event_add_movieActionPerformed

    private void rent_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rent_movieActionPerformed
            new Home_Screen().setVisible(true);
            screen.setVisible(false);
    }//GEN-LAST:event_rent_movieActionPerformed

    private void Return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_btnActionPerformed
            new return_screen().setVisible(true);
            screen.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Return_btnActionPerformed

    private void all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_btnActionPerformed
            new all_movies().setVisible(true);
            screen.setVisible(false);
    }//GEN-LAST:event_all_btnActionPerformed

    private void all_rec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_rec_btnActionPerformed
                    new Rented_Movies().setVisible(true);
            screen.setVisible(false);

    }//GEN-LAST:event_all_rec_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    JFrame screen;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Return_btn;
    private javax.swing.JButton add_movie;
    private javax.swing.JButton all_btn;
    private javax.swing.JButton all_rec_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rent_movie;
    // End of variables declaration//GEN-END:variables
}
